# -*- coding: utf-8 -*-

# Change this value to switch the UI language.
LANGUAGE = "en"

STRINGS = {
    "en": {
        "Filter Standardizer - pyMENVIC": "Filter Standardizer - pyMENVIC",
        "FILTER STANDARDIZER - pyMENVIC": "FILTER STANDARDIZER - pyMENVIC",
        "Search Text filtra la tabla y tambien sirve como texto a reemplazar cuando activas replace.": "Search Text filters the table and also acts as the replace source when replace is enabled.",
        "TOTAL": "TOTAL",
        "VISIBLE": "VISIBLE",
        "READY": "READY",
        "NO CHANGE": "NO CHANGE",
        "ISSUES": "ISSUES",
        "SEARCH TEXT": "SEARCH TEXT",
        "REPLACE WITH": "REPLACE WITH",
        "ROW FILTER": "ROW FILTER",
        "ENABLE FIND + REPLACE": "ENABLE FIND + REPLACE",
        "VIEW TYPE SUGGESTIONS: PER ROW": "VIEW TYPE SUGGESTIONS: PER ROW",
        "CONVERT ALL NEW NAMES TO UPPERCASE": "CONVERT ALL NEW NAMES TO UPPERCASE",
        "EDITABLE PREVIEW": "EDITABLE PREVIEW",
        "Edita New Name, usa sugerencias por fila y luego aplica solo filas Ready.": "Edit New Name, use suggestions per row, then apply only Ready rows.",
        "CHECK ALL VISIBLE": "CHECK ALL VISIBLE",
        "APPLY": "APPLY",
        "CURRENT NAME": "CURRENT NAME",
        "VIEW TYPE SUGGESTION": "VIEW TYPE SUGGESTION",
        "USE": "USE",
        "RESET": "RESET",
        "NEW NAME": "NEW NAME",
        "STATUS": "STATUS",
        "Flujo: filtrar con Search Text, activar replace si hace falta, generar preview, editar y aplicar.": "Flow: filter with Search Text, enable replace if needed, preview, edit, and apply.",
        "VIEW TYPES: 0/0": "VIEW TYPES: 0/0",
        "Abrir View Type Diagnostic": "Open View Type Diagnostic",
        "EDIT TYPES": "EDIT TYPES",
        "Renombrar un View Type de Section": "Rename a View Type",
        "PREVIEW": "PREVIEW",
        "CLOSE": "CLOSE",
        "Edit View Types - pyMENVIC": "Edit View Types - pyMENVIC",
        "EDIT VIEW TYPES": "EDIT VIEW TYPES",
        "Edita nombres reales de View Types. Solo filas Ready se aplican.": "Edit real View Type names. Only Ready rows are applied.",
        "SEARCH TYPE": "SEARCH TYPE",
        "VIEW FAMILY": "VIEW FAMILY",
        "CHECK CHANGED": "CHECK CHANGED",
        "CHECK EDITED": "CHECK EDITED",
        "TYPE NAME": "TYPE NAME",
        "VALIDATE": "VALIDATE",
        "Tip: valida antes de aplicar si editaste muchos nombres.": "Tip: validate before applying if you edited many names.",
        "Only Ready rows will be renamed.": "Only Ready rows will be renamed.",
        "All Rows": "All Rows",
        "Only Checked": "Only Checked",
        "Only Ready": "Only Ready",
        "Only No Change": "Only No Change",
        "Only Issues": "Only Issues",
        "Only Changed": "Only Changed",
        "All View Families": "All View Families"
    },
    "es": {
        "Filter Standardizer - pyMENVIC": "Estandarizador de Filtros - pyMENVIC",
        "FILTER STANDARDIZER - pyMENVIC": "ESTANDARIZADOR DE FILTROS - pyMENVIC",
        "Search Text filtra la tabla y tambien sirve como texto a reemplazar cuando activas replace.": "Search Text filtra la tabla y tambien sirve como texto a reemplazar cuando activas replace.",
        "TOTAL": "TOTAL",
        "VISIBLE": "VISIBLE",
        "READY": "LISTO",
        "NO CHANGE": "SIN CAMBIO",
        "ISSUES": "PROBLEMAS",
        "SEARCH TEXT": "TEXTO A BUSCAR",
        "REPLACE WITH": "REEMPLAZAR CON",
        "ROW FILTER": "FILTRO DE FILAS",
        "ENABLE FIND + REPLACE": "ACTIVAR BUSCAR + REEMPLAZAR",
        "VIEW TYPE SUGGESTIONS: PER ROW": "SUGERENCIAS VIEW TYPE: POR FILA",
        "CONVERT ALL NEW NAMES TO UPPERCASE": "CONVERTIR NEW NAME A MAYUSCULAS",
        "EDITABLE PREVIEW": "VISTA PREVIA EDITABLE",
        "Edita New Name, usa sugerencias por fila y luego aplica solo filas Ready.": "Edita New Name, usa sugerencias por fila y luego aplica solo filas listas.",
        "CHECK ALL VISIBLE": "MARCAR VISIBLES",
        "APPLY": "APLICAR",
        "CURRENT NAME": "NOMBRE ACTUAL",
        "VIEW TYPE SUGGESTION": "SUGERENCIA VIEW TYPE",
        "USE": "USAR",
        "RESET": "RESET",
        "NEW NAME": "NOMBRE NUEVO",
        "STATUS": "ESTADO",
        "Flujo: filtrar con Search Text, activar replace si hace falta, generar preview, editar y aplicar.": "Flujo: filtrar con Search Text, activar replace si hace falta, generar preview, editar y aplicar.",
        "VIEW TYPES: 0/0": "VIEW TYPES: 0/0",
        "Abrir View Type Diagnostic": "Abrir diagnostico de View Types",
        "EDIT TYPES": "EDITAR TYPES",
        "Renombrar un View Type de Section": "Renombrar View Types",
        "PREVIEW": "PREVIEW",
        "CLOSE": "CERRAR",
        "Edit View Types - pyMENVIC": "Editar View Types - pyMENVIC",
        "EDIT VIEW TYPES": "EDITAR VIEW TYPES",
        "Edita nombres reales de View Types. Solo filas Ready se aplican.": "Edita nombres reales de View Types. Solo filas listas se aplican.",
        "SEARCH TYPE": "BUSCAR TYPE",
        "VIEW FAMILY": "VIEW FAMILY",
        "CHECK CHANGED": "MARCAR CAMBIADOS",
        "CHECK EDITED": "MARCAR EDITADOS",
        "TYPE NAME": "NOMBRE TYPE",
        "VALIDATE": "VALIDAR",
        "Tip: valida antes de aplicar si editaste muchos nombres.": "Tip: valida antes de aplicar si editaste muchos nombres.",
        "Only Ready rows will be renamed.": "Solo las filas listas seran renombradas.",
        "All Rows": "Todas las filas",
        "Only Checked": "Solo marcadas",
        "Only Ready": "Solo listas",
        "Only No Change": "Solo sin cambio",
        "Only Issues": "Solo problemas",
        "Only Changed": "Solo cambiadas",
        "All View Families": "Todas las View Families"
    }
}


