# -*- coding: utf-8 -*-

LANGUAGE = "en"

STRINGS = {
    "en": {
        "Manage Filters": "Manage Filters",
        "MANAGE FILTERS": "MANAGE FILTERS",
        "Review filter usage, find unused or duplicate filters, and purge selected unused filters.": "Review filter usage, find unused or duplicate filters, and purge selected unused filters.",
        "FILTERS": "FILTERS",
        "VISIBLE": "VISIBLE",
        "UNUSED": "UNUSED",
        "DUPLICATES": "DUPLICATES",
        "SEARCH": "SEARCH",
        "SCOPE": "SCOPE",
        "REFRESH": "REFRESH",
        "CHECK VISIBLE": "CHECK VISIBLE",
        "PREVIEW": "PREVIEW",
        "Review filters before deleting. Only unused filters can be purged.": "Review filters before deleting. Only unused filters can be purged.",
        "Edit filter names here. Changed rows are checked automatically and can be saved with Save Renames.": "Edit filter names here. Changed rows are checked automatically and can be saved with Save Renames.",
        "APPLY": "APPLY",
        "FILTER NAME": "FILTER NAME",
        "VIEWS": "VIEWS",
        "TEMPLATES": "TEMPLATES",
        "TOTAL USES": "TOTAL USES",
        "STATUS": "STATUS",
        "DUPLICATE GROUP": "DUPLICATE GROUP",
        "DUPLICATE TYPE": "DUPLICATE TYPE",
        "Purge the checked unused filters only.": "Purge the checked unused filters only.",
        "Edited names can be saved with Save Renames. Purge still deletes checked unused filters only.": "Edited names can be saved with Save Renames. Purge still deletes checked unused filters only.",
        "SAVE RENAMES": "SAVE RENAMES",
        "PURGE SELECTED": "PURGE SELECTED",
        "CLOSE": "CLOSE",
        "All Filters": "All Filters",
        "Unused Only": "Unused Only",
        "Used Only": "Used Only",
        "Duplicates Only": "Duplicates Only",
        "Unused": "Unused",
        "Used": "Used",
        "Duplicate": "Duplicate",
        "Duplicate + Unused": "Duplicate + Unused",
        "Rename Pending": "Rename Pending",
        "Name Duplicate": "Name Duplicate",
        "Rule Duplicate": "Rule Duplicate",
        "Exact Match": "Exact Match",
        "Not duplicate": "Not duplicate",
        "No filters were found in this project.": "No filters were found in this project.",
        "No filters match the current criteria.": "No filters match the current criteria.",
        "No edited filter names are ready to save.": "No edited filter names are ready to save.",
        "No unused checked filters are ready to purge.": "No unused checked filters are ready to purge.",
        "Save {0} filter renames?": "Save {0} filter renames?",
        "Empty filter name: {0}": "Empty filter name: {0}",
        "Name already exists: {0}": "Name already exists: {0}",
        "Filter not found: {0}": "Filter not found: {0}",
        "Process finished.\n\nSaved renames: {0}": "Process finished.\n\nSaved renames: {0}",
        "Purge {0} unused filters?\n\nThis action cannot be undone.": "Purge {0} unused filters?\n\nThis action cannot be undone.",
        "Process finished.\n\nPurged: {0}": "Process finished.\n\nPurged: {0}",
        "\nSkipped: {0}\n\n{1}": "\nSkipped: {0}\n\n{1}",
        "Filter Usage Preview": "Filter Usage Preview",
        "No views or templates use the selected filter.": "No views or templates use the selected filter."
    },
    "es": {
        "Manage Filters": "Gestionar filtros",
        "MANAGE FILTERS": "GESTIONAR FILTROS",
        "Review filter usage, find unused or duplicate filters, and purge selected unused filters.": "Revisa el uso de filtros, encuentra filtros sin uso o duplicados y elimina los filtros sin uso seleccionados.",
        "FILTERS": "FILTROS",
        "VISIBLE": "VISIBLES",
        "UNUSED": "SIN USO",
        "DUPLICATES": "DUPLICADOS",
        "SEARCH": "BUSCAR",
        "SCOPE": "ALCANCE",
        "REFRESH": "ACTUALIZAR",
        "CHECK VISIBLE": "MARCAR VISIBLES",
        "PREVIEW": "PREVIEW",
        "Review filters before deleting. Only unused filters can be purged.": "Revisa los filtros antes de borrar. Solo se pueden eliminar filtros sin uso.",
        "Edit filter names here. Changed rows are checked automatically and can be saved with Save Renames.": "Edita aqui los nombres. Las filas cambiadas se marcan solas y se guardan con Guardar cambios.",
        "APPLY": "APLICAR",
        "FILTER NAME": "NOMBRE FILTRO",
        "VIEWS": "VISTAS",
        "TEMPLATES": "TEMPLATES",
        "TOTAL USES": "USOS TOTALES",
        "STATUS": "ESTADO",
        "DUPLICATE GROUP": "GRUPO DUPLICADO",
        "DUPLICATE TYPE": "TIPO DUPLICADO",
        "Purge the checked unused filters only.": "Elimina solo los filtros sin uso que esten marcados.",
        "Edited names can be saved with Save Renames. Purge still deletes checked unused filters only.": "Los nombres editados se guardan con Guardar cambios. Eliminar sigue borrando solo filtros sin uso marcados.",
        "SAVE RENAMES": "GUARDAR CAMBIOS",
        "PURGE SELECTED": "ELIMINAR SELECCIONADOS",
        "CLOSE": "CERRAR",
        "All Filters": "Todos los filtros",
        "Unused Only": "Solo sin uso",
        "Used Only": "Solo usados",
        "Duplicates Only": "Solo duplicados",
        "Unused": "Sin uso",
        "Used": "Usado",
        "Duplicate": "Duplicado",
        "Duplicate + Unused": "Duplicado + Sin uso",
        "Rename Pending": "Renombre pendiente",
        "Name Duplicate": "Duplicado por nombre",
        "Rule Duplicate": "Duplicado por reglas",
        "Exact Match": "Coincidencia exacta",
        "Not duplicate": "No duplicado",
        "No filters were found in this project.": "No se encontraron filtros en este proyecto.",
        "No filters match the current criteria.": "Ningun filtro coincide con los criterios actuales.",
        "No edited filter names are ready to save.": "No hay nombres editados listos para guardar.",
        "No unused checked filters are ready to purge.": "No hay filtros sin uso marcados listos para eliminar.",
        "Save {0} filter renames?": "¿Guardar {0} renombres de filtros?",
        "Empty filter name: {0}": "Nombre de filtro vacio: {0}",
        "Name already exists: {0}": "Ese nombre ya existe: {0}",
        "Filter not found: {0}": "No se encontro el filtro: {0}",
        "Process finished.\n\nSaved renames: {0}": "Proceso terminado.\n\nRenombres guardados: {0}",
        "Purge {0} unused filters?\n\nThis action cannot be undone.": "¿Eliminar {0} filtros sin uso?\n\nEsta accion no se puede deshacer.",
        "Process finished.\n\nPurged: {0}": "Proceso terminado.\n\nEliminados: {0}",
        "\nSkipped: {0}\n\n{1}": "\nOmitidos: {0}\n\n{1}",
        "Filter Usage Preview": "Preview de uso del filtro",
        "No views or templates use the selected filter.": "Ninguna vista o template usa el filtro seleccionado."
    }
}
