# -*- coding: utf-8 -*-

LANGUAGE = "en"

STRINGS = {
    "en": {
        "Replace Filters": "Replace Filters",
        "REPLACE FILTERS IN VIEWS": "REPLACE FILTERS IN VIEWS",
        "Find where a filter is used in views and templates, then replace it while keeping graphics overrides.": "Find where a filter is used in views and templates, then replace it while keeping graphics overrides.",
        "FILTERS": "FILTERS",
        "ROWS": "ROWS",
        "READY": "READY",
        "ISSUES": "ISSUES",
        "SOURCE FILTER": "SOURCE FILTER",
        "TARGET FILTER": "TARGET FILTER",
        "REFRESH": "REFRESH",
        "INCLUDE VIEWS": "INCLUDE VIEWS",
        "INCLUDE TEMPLATES": "INCLUDE TEMPLATES",
        "IF TARGET EXISTS, KEEP IT AND REMOVE THE SOURCE FILTER": "IF TARGET EXISTS, KEEP IT AND REMOVE THE SOURCE FILTER",
        "COPY SOURCE VISIBILITY TO TARGET": "COPY SOURCE VISIBILITY TO TARGET",
        "COPY SOURCE ENABLED STATE TO TARGET": "COPY SOURCE ENABLED STATE TO TARGET",
        "MERGE IF TARGET EXISTS": "MERGE IF TARGET EXISTS",
        "COPY SOURCE VISIBLE": "COPY SOURCE VISIBLE",
        "COPY SOURCE ACTIVE": "COPY SOURCE ACTIVE",
        "PREVIEW": "PREVIEW",
        "SEARCH": "SEARCH",
        "SOURCE STATE": "SOURCE STATE",
        "TARGET STATE": "TARGET STATE",
        "Sheet helps you see where each view is placed. Target Active and Target Visible can be edited directly when the target filter already exists.": "Sheet helps you see where each view is placed. Target Active and Target Visible can be edited directly when the target filter already exists.",
        "CHECK ALL": "CHECK ALL",
        "APPLY": "APPLY",
        "VIEW": "VIEW",
        "TYPE": "TYPE",
        "SHEET": "SHEET",
        "TEMPLATE": "TEMPLATE",
        "SOURCE ACTIVE": "SOURCE ACTIVE",
        "SOURCE VISIBLE": "SOURCE VISIBLE",
        "TARGET ACTIVE": "TARGET ACTIVE",
        "TARGET VISIBLE": "TARGET VISIBLE",
        "STATUS": "STATUS",
        "NOTE": "NOTE",
        "MATCH": "MATCH",
        "ACTION": "ACTION",
        "View Template": "View Template",
        "Source Active": "Source Active",
        "Source Visible": "Source Visible",
        "Target Active": "Target Active",
        "Target Visible": "Target Visible",
        "Replace the source filter with the target only on ready rows. Existing target values can be edited directly in the grid before you apply.": "Replace the source filter with the target only on ready rows. Existing target values can be edited directly in the grid before you apply.",
        "REPLACE": "REPLACE",
        "CLOSE": "CLOSE",
        "Ready": "Ready",
        "Merge": "Merge",
        "Target exists": "Target exists",
        "Skipped": "Skipped",
        "Same filter": "Same filter",
        "Error": "Error",
        "Same": "Same",
        "Missing": "Missing",
        "Visible": "Visible",
        "Active": "Active",
        "Active + Visible": "Active + Visible",
        "Replace": "Replace",
        "Skip": "Skip",
        "Keep target": "Keep target",
        "Select": "Select",
        "Select source": "Select source",
        "Select target": "Select target",
        "Source and target are the same.": "Source and target are the same.",
        "Target exists. The values below will be applied to it and the source filter will be removed.": "Target exists. The values below will be applied to it and the source filter will be removed.",
        "This view already has the target filter.": "This view already has the target filter.",
        "Enable merge if you want to replace it anyway.": "Enable merge if you want to replace it anyway.",
        "No views or templates were found using that filter.": "No views or templates were found using that filter.",
        "Select a source filter and a target filter.": "Select a source filter and a target filter.",
        "The source filter and target filter cannot be the same.": "The source filter and target filter cannot be the same.",
        "There are no ready views to replace. Review the list or enable merge.": "There are no ready views to replace. Review the list or enable merge.",
        "Replace '{0}' with '{1}' in {2} views/templates.\nRows with issues: {3}\n\nDo you want to continue?": "Replace '{0}' with '{1}' in {2} views/templates.\nRows with issues: {3}\n\nDo you want to continue?",
        "Process finished.\n\nReplaced: {0}\nMerged: {1}": "Process finished.\n\nReplaced: {0}\nMerged: {1}",
        "\nErrors: {0}\n\n{1}": "\nErrors: {0}\n\n{1}"
    },
    "es": {
        "Replace Filters": "Reemplazar filtros",
        "REPLACE FILTERS IN VIEWS": "REEMPLAZAR FILTROS EN VISTAS",
        "Find where a filter is used in views and templates, then replace it while keeping graphics overrides.": "Busca en vistas y templates donde se usa un filtro y reemplazalo manteniendo los overrides graficos.",
        "FILTERS": "FILTROS",
        "ROWS": "FILAS",
        "READY": "LISTAS",
        "ISSUES": "PROBLEMAS",
        "SOURCE FILTER": "FILTRO ORIGEN",
        "TARGET FILTER": "FILTRO DESTINO",
        "REFRESH": "ACTUALIZAR",
        "INCLUDE VIEWS": "INCLUIR VISTAS",
        "INCLUDE TEMPLATES": "INCLUIR TEMPLATES",
        "IF TARGET EXISTS, KEEP IT AND REMOVE THE SOURCE FILTER": "SI EL DESTINO YA EXISTE, CONSERVARLO Y ELIMINAR EL FILTRO ORIGEN",
        "COPY SOURCE VISIBILITY TO TARGET": "COPIAR VISIBLE DEL ORIGEN AL DESTINO",
        "COPY SOURCE ENABLED STATE TO TARGET": "COPIAR ACTIVO DEL ORIGEN AL DESTINO",
        "MERGE IF TARGET EXISTS": "MERGE SI EL DESTINO EXISTE",
        "COPY SOURCE VISIBLE": "COPIAR VISIBLE DEL ORIGEN",
        "COPY SOURCE ACTIVE": "COPIAR ACTIVO DEL ORIGEN",
        "PREVIEW": "PREVIEW",
        "SEARCH": "BUSCAR",
        "SOURCE STATE": "ESTADO ORIGEN",
        "TARGET STATE": "ESTADO DESTINO",
        "Sheet helps you see where each view is placed. Target Active and Target Visible can be edited directly when the target filter already exists.": "La hoja te ayuda a ver donde esta colocada cada vista. Target Active y Target Visible se pueden editar directo cuando el filtro destino ya existe.",
        "CHECK ALL": "MARCAR TODO",
        "APPLY": "APLICAR",
        "VIEW": "VISTA",
        "TYPE": "TIPO",
        "SHEET": "LAMINA / HOJA",
        "TEMPLATE": "TEMPLATE",
        "SOURCE ACTIVE": "ACTIVO ORIGEN",
        "SOURCE VISIBLE": "VISIBLE ORIGEN",
        "TARGET ACTIVE": "ACTIVO DESTINO",
        "TARGET VISIBLE": "VISIBLE DESTINO",
        "STATUS": "ESTADO",
        "NOTE": "NOTA",
        "MATCH": "COINCIDE",
        "ACTION": "ACCION",
        "View Template": "View Template",
        "Source Active": "Activo origen",
        "Source Visible": "Visible origen",
        "Target Active": "Activo destino",
        "Target Visible": "Visible destino",
        "Replace the source filter with the target only on ready rows. Existing target values can be edited directly in the grid before you apply.": "Reemplaza el filtro origen por el destino solo en filas listas. Los valores del destino existente se pueden editar directo en la grilla antes de aplicar.",
        "REPLACE": "REEMPLAZAR",
        "CLOSE": "CERRAR",
        "Ready": "Ready",
        "Merge": "Merge",
        "Target exists": "Destino existe",
        "Skipped": "Omitida",
        "Same filter": "Mismo filtro",
        "Error": "Error",
        "Same": "Igual",
        "Missing": "Falta",
        "Visible": "Visible",
        "Active": "Activo",
        "Active + Visible": "Activo + Visible",
        "Replace": "Reemplazar",
        "Skip": "Omitir",
        "Keep target": "Mantener destino",
        "Select": "Seleccionar",
        "Select source": "Selecciona origen",
        "Select target": "Selecciona destino",
        "Source and target are the same.": "El origen y el destino son iguales.",
        "Target exists. The values below will be applied to it and the source filter will be removed.": "El destino ya existe. Los valores de abajo se aplicaran al destino y luego se eliminara el filtro origen.",
        "This view already has the target filter.": "La vista ya tiene el filtro destino.",
        "Enable merge if you want to replace it anyway.": "Activa merge si quieres reemplazar igual.",
        "No views or templates were found using that filter.": "No se encontraron vistas o templates usando ese filtro.",
        "Select a source filter and a target filter.": "Selecciona un filtro origen y un filtro destino.",
        "The source filter and target filter cannot be the same.": "El filtro origen y el filtro destino no pueden ser el mismo.",
        "There are no ready views to replace. Review the list or enable merge.": "No hay vistas listas para reemplazar. Revisa la lista o activa merge.",
        "Replace '{0}' with '{1}' in {2} views/templates.\nRows with issues: {3}\n\nDo you want to continue?": "Se reemplazara '{0}' por '{1}' en {2} vistas/templates.\nFilas con problemas: {3}\n\n¿Deseas continuar?",
        "Process finished.\n\nReplaced: {0}\nMerged: {1}": "Proceso terminado.\n\nReemplazadas: {0}\nCon merge: {1}",
        "\nErrors: {0}\n\n{1}": "\nErrores: {0}\n\n{1}"
    }
}
