# -*- coding: utf-8 -*-

STRINGS = {
    "en": {
        "Sync Link Worksets - pyMENVIC": "Sync Link Worksets - pyMENVIC",
        "SYNC LINK WORKSETS": "SYNC LINK WORKSETS",
        "Detect worksets in loaded links, filter the list, and create only the selected ones in the host model.": "Detect worksets in loaded links, filter the list, and create only the selected ones in the host model.",
        "WORKSETS: {0}/{1}": "WORKSETS: {0}/{1}",
        "LINKS: {0}": "LINKS: {0}",
        "LINK FILTER": "LINK FILTER",
        "SEARCH WORKSET": "SEARCH WORKSET",
        "ONLY MISSING": "ONLY MISSING",
        "REFRESH": "REFRESH",
        "USE": "USE",
        "WORKSET": "WORKSET",
        "STATUS": "STATUS",
        "SOURCE LINKS": "SOURCE LINKS",
        "LINKS": "LINKS",
        "Only missing checked rows will be created.": "Only missing checked rows will be created.",
        "CHECK VISIBLE": "CHECK VISIBLE",
        "UNCHECK VISIBLE": "UNCHECK VISIBLE",
        "CHECK MISSING": "CHECK MISSING",
        "CREATE SELECTED": "CREATE SELECTED",
        "CLOSE": "CLOSE",
        "ALL LINKS": "ALL LINKS",
        "Missing": "Missing",
        "Exists": "Exists",
        "Select mode": "Select mode",
        "RUN: CREATE MISSING WORKSETS": "RUN: CREATE MISSING WORKSETS",
        "PROBE: LIST LINK WORKSETS": "PROBE: LIST LINK WORKSETS",
        "PROBE: LIST UNUSED HOST WORKSETS": "PROBE: LIST UNUSED HOST WORKSETS",
        "RUN: DELETE UNUSED HOST WORKSETS": "RUN: DELETE UNUSED HOST WORKSETS",
        "CANCEL": "CANCEL",
        "Model is not workshared.": "Model is not workshared.",
        "Could not read loaded links.": "Could not read loaded links.",
        "No missing worksets were found.": "No missing worksets were found.",
        "No rows are selected.": "No rows are selected.",
        "No checked rows are missing. Nothing was created.": "No checked rows are missing. Nothing was created.",
        "Create Worksets": "Create Worksets",
        "{0} worksets created.": "{0} worksets created.",
        "Delete worksets is not implemented in this version.": "Delete worksets is not implemented in this version.",
        "Detected worksets in links": "Detected worksets in links",
        "Host worksets": "Host worksets",
        "Link": "Link",
        "Workset": "Workset",
        "State": "State",
        "Already exists": "Already exists",
        "Missing to create": "Missing to create",
        "Scanned links: {0}": "Scanned links: {0}",
        "Skipped links: {0}": "Skipped links: {0}"
    },
    "es": {
        "Sync Link Worksets - pyMENVIC": "Sync Link Worksets - pyMENVIC",
        "SYNC LINK WORKSETS": "SINCRONIZAR WORKSETS DE LINKS",
        "Detect worksets in loaded links, filter the list, and create only the selected ones in the host model.": "Detecta worksets en links cargados, filtra la lista y crea solo los seleccionados en el modelo host.",
        "WORKSETS: {0}/{1}": "WORKSETS: {0}/{1}",
        "LINKS: {0}": "LINKS: {0}",
        "LINK FILTER": "FILTRO DE LINK",
        "SEARCH WORKSET": "BUSCAR WORKSET",
        "ONLY MISSING": "SOLO FALTANTES",
        "REFRESH": "ACTUALIZAR",
        "USE": "USAR",
        "WORKSET": "WORKSET",
        "STATUS": "ESTADO",
        "SOURCE LINKS": "LINKS ORIGEN",
        "LINKS": "LINKS",
        "Only missing checked rows will be created.": "Solo se crearan las filas marcadas que aun faltan en el host.",
        "CHECK VISIBLE": "MARCAR VISIBLES",
        "UNCHECK VISIBLE": "DESMARCAR VISIBLES",
        "CHECK MISSING": "MARCAR FALTANTES",
        "CREATE SELECTED": "CREAR SELECCIONADOS",
        "CLOSE": "CERRAR",
        "ALL LINKS": "TODOS LOS LINKS",
        "Missing": "Missing",
        "Exists": "Exists",
        "Select mode": "Selecciona modo",
        "RUN: CREATE MISSING WORKSETS": "RUN: CREAR WORKSETS FALTANTES",
        "PROBE: LIST LINK WORKSETS": "PROBE: LISTAR WORKSETS DE LINKS",
        "PROBE: LIST UNUSED HOST WORKSETS": "PROBE: LISTAR WORKSETS HOST",
        "RUN: DELETE UNUSED HOST WORKSETS": "RUN: ELIMINAR WORKSETS NO USADOS",
        "CANCEL": "CANCELAR",
        "Model is not workshared.": "El modelo no es workshared.",
        "Could not read loaded links.": "No se pudieron leer los links cargados.",
        "No missing worksets were found.": "No hay worksets faltantes por crear.",
        "No rows are selected.": "No hay filas seleccionadas.",
        "No checked rows are missing. Nothing was created.": "No hay filas marcadas faltantes. No se creo nada.",
        "Create Worksets": "Crear Worksets",
        "{0} worksets created.": "{0} worksets creados.",
        "Delete worksets is not implemented in this version.": "Delete worksets no implementado en esta version.",
        "Detected worksets in links": "Worksets detectados en links",
        "Host worksets": "Worksets host",
        "Link": "Link",
        "Workset": "Workset",
        "State": "Estado",
        "Already exists": "Ya existe",
        "Missing to create": "Falta crear",
        "Scanned links: {0}": "Links escaneados: {0}",
        "Skipped links: {0}": "Links omitidos: {0}"
    }
}
